version: '3.8'

services:
  web:
    build: .
    ports:
      - "5050:5050"
    volumes:
      - app_logs:/app/logs
    env_file:
      - .env
    restart: always

volumes:
  app_logs:
    driver: local
